-- Fresh Supabase PostgreSQL schema for the Jukebox booking system.
-- Run this file in Supabase Dashboard > SQL Editor before deploying the API.
-- Times stored in slot_time are Singapore wall-clock booking times.

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'individual'
        CHECK (role IN ('admin', 'band', 'individual')),
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'approved', 'rejected', 'suspended')),
    is_mr_certified BOOLEAN NOT NULL DEFAULT FALSE,
    band_id INTEGER,
    telegram_chat_id BIGINT,
    username_change_count INTEGER NOT NULL DEFAULT 0,
    last_username_changed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS bands (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    leader_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    band_type VARCHAR(20) NOT NULL DEFAULT 'standard'
        CHECK (band_type IN ('standard', 'cbtr', 'low_priority')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    band_name_change_count INTEGER NOT NULL DEFAULT 0,
    last_band_name_changed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bids (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id INTEGER NOT NULL REFERENCES bands(id) ON DELETE CASCADE,
    slot_date DATE NOT NULL,
    slot_time TIME NOT NULL
        CHECK (slot_time IN (
            TIME '07:00', TIME '09:00', TIME '11:00', TIME '13:00',
            TIME '15:00', TIME '17:00', TIME '19:00', TIME '21:00'
        )),
    preference_rank INTEGER NOT NULL CHECK (preference_rank BETWEEN 1 AND 3),
    bid_value INTEGER NOT NULL,
    allocation_status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (allocation_status IN ('pending', 'won', 'lost')),
    reject_reason_category VARCHAR(30)
        CHECK (reject_reason_category IS NULL OR reject_reason_category IN (
            'cascading_priority', 'random_tie', 'low_bid_point'
        )),
    reject_reason VARCHAR(255),
    allocation_run_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (band_id, slot_date, slot_time)
);

CREATE TABLE IF NOT EXISTS bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id INTEGER REFERENCES bands(id) ON DELETE SET NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    booking_type VARCHAR(20) NOT NULL DEFAULT 'band'
        CHECK (booking_type IN ('band', 'individual')),
    slot_category VARCHAR(20)
        CHECK (slot_category IS NULL OR slot_category IN ('primary', 'extra')),
    slot_date DATE NOT NULL,
    slot_time TIME NOT NULL
        CHECK (slot_time IN (
            TIME '07:00', TIME '09:00', TIME '11:00', TIME '13:00',
            TIME '15:00', TIME '17:00', TIME '19:00', TIME '21:00'
        )),
    allocation_score INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN (
            'pending', 'confirmed', 'rejected', 'cancelled',
            'late_cancelled', 'displaced'
        )),
    reject_reason VARCHAR(255),
    cancel_reason VARCHAR(255),
    notes TEXT,
    humidifier_photo_url VARCHAR(500),
    humidifier_photo_uploaded_at TIMESTAMPTZ,
    humidifier_flagged INTEGER NOT NULL DEFAULT 0
        CHECK (humidifier_flagged IN (0, 1)),
    cancelled_at TIMESTAMPTZ,
    is_late_cancellation BOOLEAN NOT NULL DEFAULT FALSE,
    band_confirmation_status VARCHAR(20)
        CHECK (band_confirmation_status IS NULL OR band_confirmation_status IN (
            'pending', 'confirmed', 'released'
        )),
    band_confirmation_deadline TIMESTAMPTZ,
    band_confirmed_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    release_reason VARCHAR(255),
    reminder_sent INTEGER NOT NULL DEFAULT 0 CHECK (reminder_sent IN (0, 1)),
    google_calendar_event_id VARCHAR(255),
    google_calendar_event_link TEXT,
    calendar_sync_status VARCHAR(20) NOT NULL DEFAULT 'not_synced'
        CHECK (calendar_sync_status IN ('not_synced', 'synced', 'deleted', 'failed', 'skipped')),
    calendar_sync_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (booking_type = 'band' AND band_id IS NOT NULL) OR
        (booking_type = 'individual' AND user_id IS NOT NULL)
    )
);

-- Enforce one currently confirmed booking per room slot, while retaining
-- cancelled/displaced booking history.
CREATE UNIQUE INDEX IF NOT EXISTS bookings_one_confirmed_per_slot
    ON bookings (slot_date, slot_time)
    WHERE status = 'confirmed';

CREATE INDEX IF NOT EXISTS bookings_user_date_idx
    ON bookings (user_id, slot_date);

CREATE INDEX IF NOT EXISTS bookings_band_date_idx
    ON bookings (band_id, slot_date);

CREATE TABLE IF NOT EXISTS bidding_windows (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_week_monday DATE NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'closed')),
    opened_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS band_members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id INTEGER NOT NULL REFERENCES bands(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    member_role VARCHAR(20) NOT NULL DEFAULT 'member'
        CHECK (member_role IN ('leader', 'member')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (band_id, user_id)
);

CREATE TABLE IF NOT EXISTS email_otps (
    email VARCHAR(255) PRIMARY KEY,
    otp_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_reset_otps (
    email VARCHAR(255) PRIMARY KEY,
    otp_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS bidding_windows_set_updated_at ON bidding_windows;
CREATE TRIGGER bidding_windows_set_updated_at
BEFORE UPDATE ON bidding_windows
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS system_settings_set_updated_at ON system_settings;
CREATE TRIGGER system_settings_set_updated_at
BEFORE UPDATE ON system_settings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO system_settings (setting_key, setting_value)
VALUES ('holiday_mode', 'false')
ON CONFLICT (setting_key) DO NOTHING;

-- The app connects directly from the trusted Render server. No browser-side
-- Supabase credentials are used, so keep the Data API locked down by default.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE bands ENABLE ROW LEVEL SECURITY;
ALTER TABLE bids ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE bidding_windows ENABLE ROW LEVEL SECURITY;
ALTER TABLE band_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_otps ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_otps ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
