-- Historical migration retained for context only.
--
-- The Supabase deployment is intentionally a fresh PostgreSQL database, and
-- server/schema.sql already permits only the new 07:00 through 21:00 starts.
-- Do not run a slot-shift migration on the fresh database.
